---

- name: Create a volume group {{ k8s_nbd_idlocal }} and resize it the maximum possible
  community.general.lvg:
    vg: "{{ k8s_nbd_idlocal }}"
    pvs: "{{ disks }}"
    pvresize: yes

#- name: Create a thin volume
#  community.general.lvol:
#    vg: "{{ k8s_nbd_idlocal }}"
#    thinpool: thinpool
#    size: 99%VG
