---
- name: Setup srv
  hosts: srve
  become: true
  roles:
    - gresolver
    - proxy
    - wg

- name: Bootstrap hosts
  hosts: ansibled
  become: true
  roles:
    - gresolver
    - hostname
    - net_conf
    - wg_route
    - proxified_pkg
    - common
    - swapoff

- name: Setup microk8s on srv
  hosts: srvl
  become: true
  roles:
    - snapd
    - k8s_utils
    - microk8s
    - k8s_save_conf
    - helm_repos

- name: Deploy cluster k8s (with kubespray)
  become: true
  ansible.builtin.import_playbook: ansible/kubespray/cluster.yml
  vars:
    cluster_name: "cluster.cl0.{{ dns_zone_k8s }}"
    local_path_provisioner_enabled: true
    local_path_provisioner_is_default_storageclass: false
    local_volume_provisioner_enabled: true
    local_volume_provisioner_use_node_name_only: false
    metrics_server_enabled: true
    metrics_server_kubelet_insecure_tls: true
    metrics_server_metric_resolution: 15s
    metrics_server_kubelet_preferred_address_types: "InternalIP"
    nodelocaldns_external_zones:
      - zones:
        - "{{ dns_zone_srv }}"
        - "{{ dns_zone_k8s }}"
        nameservers:
        - "{{ var_priv_dns }}"

- name: SF ansible tasks - get k8s configs
  hosts: srvl,masters
  become: true
  roles:
    - k8s_save_conf

